use_frameworks!

platform :ios, '9.0'

target 'Hi-Router-Module_Example' do
  pod 'Hi-Router-Module', :path => '../'

  target 'Hi-Router-Module_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
